### ISSUE TITLE
User account privileges

### ISSUE THREAD

**Issue by mimidotsuser** [crane-cloud/backend#275]
Currently, any authenticated user can fetch all the available roles. 
Also, they can update any profile access role as the resource methods don't require admin privilege.

https://github.com/crane-cloud/backend/blob/557acb6b915e5ca3c1bd5044db5f709dc2b9e63b/app/controllers/user_role.py#L13

Is this behavior intentional?

**Comment by neelxie** [comment]
Thank you @mimidotsuser for pointing this out, of course, it was not intentional. The team is currently working to have this fixed as soon as possible. Thank you again.

**Comment by neelxie** [comment]
@mimidotsuser This was fixed.
